version: '3.12'

services:
  web:
    build: .
    container_name: weather_web_container
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=favourite_cities
      - DB_USER=postgres
      - DB_PASSWORD=Akshay
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:7000"
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    networks:
      - weather_net
    
    
  postgres_db:
    container_name: weather_postgres_container
    image: postgres:16-bullseye
    volumes:
      - wetaher_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: favourite_cities
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Akshay
    networks:
      - weather_net

networks:
  weather_net:
    driver: bridge

volumes:
 wetaher_postgres_data:
