# Generated by Django 5.0.4 on 2024-04-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_userdetails_otp_remove_userdetails_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
