# Generated by Django 5.0.4 on 2024-04-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_favouritecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='image_url',
            field=models.URLField(default='null'),
        ),
    ]
